pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: squash
  - name: Automatic update to the main branch for pull requests
    conditions:
      - -conflict
      - -draft
      - -author=dependabot[bot]
    actions:
      update:
  - name: Automatically approve Dependabot PRs that does not bump major
    conditions:
      - author=dependabot[bot]
      - dependabot-update-type = version-update:semver-minor
    actions:
      review:
        type: APPROVE
  - name: Automatically approve Dependabot PRs that does not bump major
    conditions:
      - author=dependabot[bot]
      - dependabot-update-type = version-update:semver-patch
    actions:
      review:
        type: APPROVE
