pull_request_rules:
  - name: Automatically approve Dependabot PRs bumping minor
    conditions:
      - author=dependabot[bot]
      - dependabot-update-type = version-update:semver-minor
    actions:
      review:
        type: APPROVE
  - name: Automatically approve Dependabot PRs bumping patch
    conditions:
      - author=dependabot[bot]
      - dependabot-update-type = version-update:semver-patch
    actions:
      review:
        type: APPROVE
  - name: Queue pull requests targeting main
    conditions:
      - base=main
      - -draft
      - -conflict
    actions:
      queue:
        name: default

queue_rules:
  - name: default
    conditions:
      - base=main
      - -draft
      - -conflict
      - status-success
      - "#approved-reviews-by>=1"
