# FINAL arch images
FROM --platform=amd64 gcr.io/distroless/cc-debian11 as final-amd64
COPY target/x86_64-unknown-linux-gnu/release/unleash-edge /unleash-edge

FROM --platform=arm64 gcr.io/distroless/cc-debian11 as final-arm64
COPY target/aarch64-unknown-linux-gnu/release/unleash-edge /unleash-edge

# Final image

FROM final-${TARGETARCH}

RUN apt install libssl-dev

ENTRYPOINT [ "/unleash-edge" ]
