# FINAL arch images
FROM --platform=amd64 debian:12-slim as final-amd64
COPY target/x86_64-unknown-linux-gnu/release/unleash-edge /unleash-edge

FROM --platform=arm64 debian:12-slim as final-arm64
COPY target/aarch64-unknown-linux-gnu/release/unleash-edge /unleash-edge

# Final image
FROM final-${TARGETARCH}

RUN apt update
RUN apt install -y curl jq less telnet

ENV RUST_LOG=DEBUG
WORKDIR /
ENTRYPOINT [ "/unleash-edge" ]
