[package]
name = "unleash-edge-context-enrichers"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
publish = false
license-file = "../../../LICENSE-ENTERPRISE.md"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
unleash-types = { workspace = true }