[package]
name = "unleash-edge-backstage"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
publish = true
license.workspace = true

[dependencies]
axum = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
unleash-edge-appstate = { workspace = true }
unleash-edge-auth = { workspace = true }
unleash-edge-cli = { workspace = true }
unleash-edge-feature-refresh = { workspace = true }
unleash-edge-feature-cache = { workspace = true }
unleash-edge-http-client = { workspace = true }
unleash-edge-persistence = { workspace = true }
unleash-edge-types = { workspace = true }
unleash-types = { workspace = true }
