version: "3.8"
services:
  unleash:
    image: unleashorg/unleash-server:latest
    pull_policy: always
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: "postgres://postgres:unleash@db/db"
      DATABASE_SSL: "false"
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"
    depends_on:
      - db
    command: ["node", "index.js"]
  db:
    expose:
      - "5432"
    image: postgres:15
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres", "--host=127.0.0.1", "--port=5432"]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
  edge:
    image: unleashorg/unleash-edge:latest
    pull_policy: always
    restart: always
    depends_on:
      - unleash
    environment:
      UPSTREAM_URL: http://unleash:4242
      TOKENS: "default:development.unleash-insecure-api-token"
      REDIS_URL: redis://redis:6379
    ports:
      - "3063:3063"
    command: ["edge"]
    healthcheck:
      test: ["CMD", "/unleash-edge", "health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
