cargo-features = ["codegen-backend"]

[env]
CC_aarch64_unknown_linux_musl = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# Default dev - fallback to LLVM
[profile.dev]

[profile.dev.package."*".codegen-backend.'cfg(env("CRANELIFT_BUILD", "1"))']
codegen-backend = "cranelift"

[profile.dev.codegen-backend.'cfg(env("CRANELIFT_BUILD", "1"))']
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"