[package]
name = "unleash-edge-edge-api"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
publish = true
license.workspace = true

[dependencies]
axum = { workspace = true }
unleash-edge-appstate = { workspace = true }
unleash-edge-auth = { workspace = true }
unleash-edge-types = { workspace = true }
utoipa = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
