---
name: Build main - docker image for DockerHub and AWS public gallery
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "**/*.toml"
      - ".github/workflows/build-docker-release.yaml"

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  dockerpublish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile default
          rustup show
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-v0-gnu"
      - name: Install cross (cross compile)
        run: |
          cargo install cross
      - name: Build release for x86_64
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu
      - name: Build release for aarch64
        run: |
          cross build --release --target=aarch64-unknown-linux-gnu
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::726824350591:role/unleash-github-ecr-public-publish-role
          role-session-name: edge-actions-push-to-ecr-public
          aws-region: us-east-1
      - name: Login to AWS ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Docker meta configuration (set image and tag)
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            unleashorg/unleash-edge
            ${{ steps.login-ecr-public.outputs.registry }}/unleashorg/unleash-edge
          tags: |
            type=edge

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tag and push images
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.publish
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
